import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

type Lang = 'fr' | 'en' | 'ar';

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    login: 'Connexion',
    register: 'Inscription',
    logout: 'Déconnexion',
    myAccount: 'Mon Compte',
    search: 'Rechercher une marque, modèle, année...',
    heroTitle: 'Votre véhicule, de France jusqu\'à',
    heroTitleAccent: 'votre porte',
    heroSubtitle: 'Importation clé-en-main de véhicules neufs et d\'occasion vers l\'Algérie. Vérifié, sécurisé, livré.',
    exploreVehicles: 'Explorer les véhicules',
    howItWorks: 'Comment ça marche',
    vehiclesImported: 'véhicules importés',
    satisfiedClients: 'clients satisfaits',
    avgDelivery: 'jours délai moyen',
    showrooms: 'Nos Showrooms',
    showroomLuxe: 'Showroom Luxe',
    showroomPopular: 'Showroom Populaire',
    promotions: 'Promotions',
    luxeDesc: 'Véhicules premium de plus de 30 000€. BMW, Mercedes, Audi, Porsche et plus.',
    popularDesc: 'Véhicules fiables entre 8 000€ et 30 000€. Renault, Peugeot, Citroën, Dacia, Toyota.',
    promoDesc: 'Véhicules en offre spéciale avec remises exclusives. Profitez-en avant qu\'il ne soit trop tard !',
    discover: 'Découvrir',
    yourTools: 'Vos Outils',
    customsCalc: 'Calculateur Douanier',
    calcDesc: 'Estimez le coût total de votre importation en DZD en temps réel. Prix du véhicule, droits de douane, TVA, TIC et frais transitaire — tout est calculé automatiquement.',
    trackerGPS: 'Tracker GPS',
    trackerDesc: 'Suivez votre véhicule en temps réel de la France jusqu\'à l\'Algérie. Carte interactive avec position maritime et estimation d\'arrivée.',
    safeBox: 'Coffre-Fort Digital',
    safeDesc: 'Stockez tous vos documents d\'importation en toute sécurité. Carte grise, factures, connaissements — chiffrés et accessibles 24h/24.',
    simulate: 'Simuler',
    track: 'Tracker',
    access: 'Accéder',
    trustUs: 'Ils nous font confiance',
    satisfaction: 'Taux de satisfaction',
    daysAvg: 'Jours moyens',
    partners: 'Partenaires',
    yearsExp: "Années d'expertise",
    navigation: 'Navigation',
    services: 'Services',
    contact: 'Contact',
    paymentSecure: 'Paiement sécurisé',
    allRights: 'Tous droits réservés',
    privacyPolicy: 'Politique de confidentialité',
    legalMentions: 'Mentions légales',
    ctaLogin: 'Se connecter',
    ctaSignup: 'Créer un compte',
    email: 'Email',
    password: 'Mot de passe',
    name: 'Nom complet',
    accountType: 'Type de compte',
    client: 'Particulier',
    garage: 'Garage / Vendeur',
    forgotPassword: 'Mot de passe oublié ?',
    alreadyAccount: 'Déjà un compte ?',
    noAccount: 'Pas encore de compte ?',
    loginRequired: 'Connexion requise',
    loginRequiredMsg: 'Veuillez vous connecter pour accéder à cette fonctionnalité.',
    bankVerify: 'Vérification Bancaire',
    bankVerifyDesc: 'Vérifiez votre compte devise pour finaliser vos transactions.',
    selectBank: 'Sélectionnez votre banque',
    accountNumber: 'Numéro de compte',
    verify: 'Vérifier',
    chatSupport: 'Support Client',
    chatPlaceholder: 'Écrivez votre message...',
    send: 'Envoyer',
    close: 'Fermer',
    welcome: 'Bienvenue',
    chatWelcome: 'Bonjour ! Comment pouvons-nous vous aider aujourd\'hui ?',
  },
  en: {
    login: 'Login',
    register: 'Sign Up',
    logout: 'Logout',
    myAccount: 'My Account',
    search: 'Search brand, model, year...',
    heroTitle: 'Your vehicle, from France to',
    heroTitleAccent: 'your doorstep',
    heroSubtitle: 'Turnkey import of new and used vehicles to Algeria. Verified, secured, delivered.',
    exploreVehicles: 'Explore Vehicles',
    howItWorks: 'How It Works',
    vehiclesImported: 'vehicles imported',
    satisfiedClients: 'satisfied clients',
    avgDelivery: 'days average delivery',
    showrooms: 'Our Showrooms',
    showroomLuxe: 'Luxury Showroom',
    showroomPopular: 'Popular Showroom',
    promotions: 'Promotions',
    luxeDesc: 'Premium vehicles over €30,000. BMW, Mercedes, Audi, Porsche and more.',
    popularDesc: 'Reliable vehicles between €8,000 and €30,000. Renault, Peugeot, Citroën, Dacia, Toyota.',
    promoDesc: 'Vehicles on special offer with exclusive discounts. Grab them before it\'s too late!',
    discover: 'Discover',
    yourTools: 'Your Tools',
    customsCalc: 'Customs Calculator',
    calcDesc: 'Estimate the total cost of your import in DZD in real time. Vehicle price, customs duties, VAT, TIC and forwarding fees — all calculated automatically.',
    trackerGPS: 'GPS Tracker',
    trackerDesc: 'Track your vehicle in real time from France to Algeria. Interactive map with maritime position and ETA.',
    safeBox: 'Digital Safe',
    safeDesc: 'Store all your import documents securely. Registration, invoices, bills of lading — encrypted and accessible 24/7.',
    simulate: 'Simulate',
    track: 'Track',
    access: 'Access',
    trustUs: 'They Trust Us',
    satisfaction: 'Satisfaction Rate',
    daysAvg: 'Avg Days',
    partners: 'Partners',
    yearsExp: 'Years Exp.',
    navigation: 'Navigation',
    services: 'Services',
    contact: 'Contact',
    paymentSecure: 'Secure Payment',
    allRights: 'All rights reserved',
    privacyPolicy: 'Privacy Policy',
    legalMentions: 'Legal Notices',
    ctaLogin: 'Sign In',
    ctaSignup: 'Create Account',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    accountType: 'Account Type',
    client: 'Individual',
    garage: 'Garage / Seller',
    forgotPassword: 'Forgot password?',
    alreadyAccount: 'Already have an account?',
    noAccount: 'No account yet?',
    loginRequired: 'Login Required',
    loginRequiredMsg: 'Please log in to access this feature.',
    bankVerify: 'Bank Verification',
    bankVerifyDesc: 'Verify your foreign currency account to finalize transactions.',
    selectBank: 'Select your bank',
    accountNumber: 'Account Number',
    verify: 'Verify',
    chatSupport: 'Customer Support',
    chatPlaceholder: 'Type your message...',
    send: 'Send',
    close: 'Close',
    welcome: 'Welcome',
    chatWelcome: 'Hello! How can we help you today?',
  },
  ar: {
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    myAccount: 'حسابي',
    search: 'ابحث عن علامة تجارية، طراز، سنة...',
    heroTitle: 'مركبتك، من فرنسا إلى',
    heroTitleAccent: 'باب منزلك',
    heroSubtitle: 'استيراد شامل للسيارات الجديدة والمستعملة إلى الجزائر. موثوق، آمن، ومسلّم.',
    exploreVehicles: 'استكشف المركبات',
    howItWorks: 'كيف يعمل',
    vehiclesImported: 'مركبة مستوردة',
    satisfiedClients: 'عميل راضٍ',
    avgDelivery: 'يوم متوسط التسليم',
    showrooms: 'معارضنا',
    showroomLuxe: 'المعرض الفاخر',
    showroomPopular: 'المعرض الشعبي',
    promotions: 'العروض',
    luxeDesc: 'مركبات فاخرة بأكثر من 30,000 يورو. بي إم دبليو، مرسيدس، أودي، بورش والمزيد.',
    popularDesc: 'مركبات موثوقة بين 8,000 و 30,000 يورو. رينو، بيجو، ستروين، داسيا، تويوتا.',
    promoDesc: 'مركبات بعروض خاصة مع خصومات حصرية. استفد منها قبل فوات الأوان!',
    discover: 'اكتشف',
    yourTools: 'أدواتك',
    customsCalc: 'حاسبة الجمارك',
    calcDesc: 'قدر التكلفة الإجمالية لاستيرادك بالدينار الجزائري في الوقت الفعلي.',
    trackerGPS: 'متتبع GPS',
    trackerDesc: 'تتبع مركبتك في الوقت الفعلي من فرنسا إلى الجزائر.',
    safeBox: 'الخزنة الرقمية',
    safeDesc: 'احفظ جميع مستندات الاستيراد بأمان. مشفرة ومتاحة 24/7.',
    simulate: 'حاكِ',
    track: 'تتبع',
    access: 'الوصول',
    trustUs: 'يثقون بنا',
    satisfaction: 'معدل الرضا',
    daysAvg: 'متوسط الأيام',
    partners: 'شركاء',
    yearsExp: 'سنوات الخبرة',
    navigation: 'التنقل',
    services: 'الخدمات',
    contact: 'اتصل',
    paymentSecure: 'دفع آمن',
    allRights: 'جميع الحقوق محفوظة',
    privacyPolicy: 'سياسة الخصوصية',
    legalMentions: 'إشارات قانونية',
    ctaLogin: 'تسجيل الدخول',
    ctaSignup: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم الكامل',
    accountType: 'نوع الحساب',
    client: 'فرد',
    garage: 'مرآب / بائع',
    forgotPassword: 'نسيت كلمة المرور؟',
    alreadyAccount: 'لديك حساب بالفعل؟',
    noAccount: 'ليس لديك حساب؟',
    loginRequired: 'تسجيل الدخول مطلوب',
    loginRequiredMsg: 'الرجاء تسجيل الدخول للوصول إلى هذه الميزة.',
    bankVerify: 'التحقق البنكي',
    bankVerifyDesc: 'تحقق من حساب العملات الأجنبية لإنهاء المعاملات.',
    selectBank: 'اختر بنكك',
    accountNumber: 'رقم الحساب',
    verify: 'تحقق',
    chatSupport: 'دعم العملاء',
    chatPlaceholder: 'اكتب رسالتك...',
    send: 'إرسال',
    close: 'إغلاق',
    welcome: 'أهلاً',
    chatWelcome: 'مرحباً! كيف يمكننا مساعدتك اليوم؟',
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LangContext = createContext<LangContextType>({
  lang: 'fr',
  setLang: () => {},
  t: (key: string) => key,
  isRTL: false,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr');

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    document.documentElement.dir = l === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = l === 'ar' ? 'ar' : l === 'en' ? 'en' : 'fr';
  }, []);

  const t = useCallback(
    (key: string) => {
      return translations[lang][key] || key;
    },
    [lang]
  );

  const isRTL = lang === 'ar';

  return (
    <LangContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
